/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_netbrace_interfaces_ChannelCommandInterface */

#ifndef _Included_org_netbrace_interfaces_ChannelCommandInterface
#define _Included_org_netbrace_interfaces_ChannelCommandInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_netbrace_interfaces_ChannelCommandInterface
 * Method:    open
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_netbrace_interfaces_ChannelCommandInterface_open
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_netbrace_interfaces_ChannelCommandInterface
 * Method:    close
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_netbrace_interfaces_ChannelCommandInterface_close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
